In [1]:
# import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler

In [2]:
# make an example dataset
df = pd.DataFrame({
    'age': [25,30,35,40,45],
    'height': [165,170,175,180,185],
    'weight': [55,60,65,70,75]
})

df.head()

   age  height  weight
0   25     165      55
1   30     170      60
2   35     175      65
3   40     180      70
4   45     185      75

In [3]:
# import the scalar
scalar = MinMaxScaler()

# fit the scalar on data
scaled_df = scalar.fit_transform(df)
# convert this data into a pandas dataframe
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

    age  height  weight
0  0.00    0.00    0.00
1  0.25    0.25    0.25
2  0.50    0.50    0.50
3  0.75    0.75    0.75
4  1.00    1.00    1.00

---